name = "biomass_docs"
uuid = "205506dd-e88c-4cb6-9215-66cd538617a8"
authors = ["Hiroaki Imoto <himoto@protein.osaka-u.ac.jp>"]
version = "0.2.0"

[deps]

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
