# This file is machine-generated - editing it directly is not advised

[[biomass_docs]]
path = "/Users/himoto/github/OkadaLab/biomass_docs"
uuid = "205506dd-e88c-4cb6-9215-66cd538617a8"
version = "0.1.0"
